title:
  - long: 'Your Article Title Here'
  - short: 'Short Title'
  - lead_author: "Author"

date: "2025-01-01"
status: "draft"
use_line_numbers: true
license: "CC BY 4.0"
acknowledge_rxiv_maker: true

keywords:
  - "keyword1"
  - "keyword2"
  - "keyword3"

authors:
  - name: "First Author"
    affiliations:
      - "Affiliation1"
    corresponding_author: true
    co_first_author: false
    email: "first.author@example.com"
    orcid: 0000-0000-0000-0000
  - name: "Second Author"
    affiliations:
      - "Affiliation2"
    corresponding_author: false
    co_first_author: false
    email: "second.author@example.com"

affiliations:
  - shortname: "Affiliation1"
    full_name: "First Institution Name"
    location: "City, Country"
  - shortname: "Affiliation2"
    full_name: "Second Institution Name"
    location: "City, Country"

bibliography: 03_REFERENCES.bib
